name: "build and deploy"
on: push
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Create .ENV
        run: |
          touch .env.production
          echo VITE_HOST=${{ secrets.VITE_HOST }} >> .env.production
          echo VITE_HOST_SOCKET=${{ secrets.VITE_HOST_SOCKET }} >> .env.production
          echo VITE_HOSTIMAGE=${{ secrets.VITE_HOSTIMAGE }} >> .env.production
          echo VITE_HOST_API=${{ secrets.VITE_HOST_API }} >> .env.production
          echo VIEW_CONSOLE=${{ secrets.VIEW_CONSOLE }} >> .env.production
          echo VITE_RECAPTCHA=${{ secrets.VITE_RECAPTCHA }} >> .env.production
          echo VITE_PORT=${{ secrets.VITE_PORT }} >> .env.production
          cat .env.production

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # password: ${{ secrets.REGISTRY_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: "build & deploy"
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          # secrets: |
          #   "MODE=Release"
          # build-args: |
          #   build_mode=Release
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create .ENV
        run: |
          touch .env.production
          echo VITE_HOST=${{ secrets.VITE_HOST }} >> .env.production
          echo VITE_HOST_SOCKET=${{ secrets.VITE_HOST_SOCKET }} >> .env.production
          echo VITE_HOSTIMAGE=${{ secrets.VITE_HOSTIMAGE }} >> .env.production
          echo VITE_HOST_API=${{ secrets.VITE_HOST_API }} >> .env.production
          echo VIEW_CONSOLE=${{ secrets.VIEW_CONSOLE }} >> .env.production
          echo VITE_RECAPTCHA=${{ secrets.VITE_RECAPTCHA }} >> .env.production
          echo VITE_PORT=${{ secrets.VITE_PORT }} >> .env.production
          cat .env.production
      - name: copy file .env on server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.SSH_SITE_HOST }}
          username: ${{ secrets.SSH_SITE_USERNAME }}
          password: ${{ secrets.SSH_SITE_PASSWORD }}
          port: ${{ secrets.SSH_SITE_PORT }}
          local: .env
          remote: .env
      - name: "Run deploy on server"
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_SITE_HOST }}
          username: ${{ secrets.SSH_SITE_USERNAME }}
          # key: ${{ secrets.SSH_SITE_TOKEN }}
          password: ${{ secrets.SSH_SITE_PASSWORD }}
          port: ${{ secrets.SSH_SITE_PORT }}
          # sudo docker rm mongodb-api
          # sudo docker rm kingwood-api-from-image
          script: |
            sudo docker-compose -f docker-compose.yml -p prod down
            sudo docker image rm ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
            sudo docker-compose -f docker-compose.yml -p prod pull
            sudo docker-compose -f docker-compose.yml -p prod up -d
