export const roles = [
  "auth-create",
  "auth-resetpass",
  "auth-block",
  "role-create",
  "role-patch",
  "role-delete",
  "role-list",
  "user-patch",
  "user-delete",
  "user-list",
  "user-archiv",
  "user-change-post",
  "user-change-typeWork",
  "user-change-typePay",
  "user-change-role",
  "object-create",
  "object-patch",
  "object-delete",
  "object-list",
  "order-create",
  "order-patch",
  "order-delete",
  "order-list",
  "order-otgruzka",
  "order-add-design",
  "order-completed",
  "task-create",
  "task-patch",
  "task-delete",
  "task-list",
  "task-maxHours",

  "taskWorker-create",
  "taskWorker-patch",
  "taskWorker-delete",
  "taskWorker-typeGo",
  "taskWorker-statusId",
  "montajList-list",
  "montajList-viewOrders",
  "post-create",
  "post-patch",
  "post-delete",
  "post-list",
  "operation-create",
  "operation-patch",
  "operation-delete",
  "operation-list",
  "taskStatus-create",
  "taskStatus-patch",
  "taskStatus-delete",
  "taskStatus-list",
  "financy-list",

  "payTemplate-create",
  "payTemplate-patch",
  "payTemplate-delete",
  "payTemplate-list",
  // "workTime-create",
  // "workTime-patch",
  // "workTime-delete",
  // "workTime-list",

  "workHistory-create",
  "workHistory-patch",
  "workHistory-delete",
  "workHistory-list",
  "workHistory-view-changes",

  "pay-patch",
  "pay-view-changes",
  "maxTime-edit",
];
