export const roles = [
  "auth-create",
  "auth-resetpass",
  "role-create",
  "role-patch",
  "role-delete",
  "user-patch",
  "user-delete",
  "object-create",
  "object-patch",
  "object-delete",
  "order-create",
  "order-patch",
  "order-delete",
  "task-create",
  "task-patch",
  "task-delete",
];
